export const ROOM_STATE_TYPE = {
  PREVIEW: "PREVIEW",
  CALL: "CALL",
  LEFT_ROOM: "LEFT_ROOM",
  NETWORK_ERROR: "NETWORK_ERROR",
}

export const ISSUE_URL = import.meta.env.VITE_ISSUE_URL

// ------- PEER LAYOUT CONSTANTS -------

const MIN_TILE_WIDTH = 200
const ASPECT_RATIO = 16 / 9

export const LAYOUT_CONSTANTS = {
  SPACING: 12,
  MIN_TILE_WIDTH,
  MIN_TILE_HEIGHT: MIN_TILE_WIDTH * (1 / ASPECT_RATIO),
  ASPECT_RATIO,
  MOBILE_BREAKPOINT: 600,
  MAX_MOBILE_PEERS: 4,
  MAX_DESKTOP_PEERS: 8,
} as const

// ---------------------------------
